name: Morning Signal Bot

on:
  schedule:
    # Runs at 08:55 CET (06:55 UTC) every weekday Mon-Fri
    - cron: "55 6 * * 1-5"
  workflow_dispatch: # manual trigger option

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Set environment variables from GitHub secrets
      - name: Set environment variables
        run: |
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> $GITHUB_ENV
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> $GITHUB_ENV
          echo "TWELVE_API_KEY=${{ secrets.TWELVE_API_KEY }}" >> $GITHUB_ENV

      # 5️⃣ Run bot and log output
      - name: Run bot
        run: |
          python bot.py | tee bot.log

      # 6️⃣ (Optional) Upload log as artifact
      - name: Upload bot log
        uses: actions/upload-artifact@v3
        with:
          name: bot-log
          path: bot.log
